[package]
org = "lakshanweerasinghe"
name = "event_driven_etl_pipeline"
version = "0.1.0"
distribution = "2201.8.6"

[build-options]
observabilityIncluded = true

[persist]
datastore = "mysql"
module = "event_driven_etl_pipeline"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.sql-native"
version = "1.2.1"

